### PR TITLE
Migrate docs to GitHub Pages

### PR DESCRIPTION
**Pull request by isakube**
This PR.. uhh.. Migrates the documentation to GitHub Pages. yeah. not much else to say here.
EDIT: reread the contribution guidelines. i dont think it likes drafts. uhhhhhh

---
RESOLVES:
- #29

---
TASK LIST SORTA:
- [x] Set up Pages environment
- [x] Get Slate theme working
- [ ] Migrate wiki to Pages environment
- [ ] Add extra guides for le modders :)

---

**PAGES CONVERTED:**
- [x] `docs/README.md` (Includes defining features of Enigma and a ModCore ad lol)
- [x] `docs/guides/modcore` (Includes a tutorial on making ModCore mods, is literally just pasted from the wiki) 
- [ ] Rest of the Wiki

### CODE REVIEW

**Comment by EliteMasterEric** [comment]
Thank you so much for the effort! I'll look at how it appears later.

I mostly copy-pasted the contribution requirements just to have some rules in place. I'm fine with drafts.

EDIT: I'll likely create a repo to use enigmaengine.github.io and move documentation there.

I wonder if I can get GitHub Pages to display the latest stable HTML5 build without too much work?

**Comment by isakube** [comment]
> EDIT: I'll likely create a repo to use enigmaengine.github.io and move documentation there.

yeah that's cool
ALSO you know how users get special repositories for the profile readme and stuff?
organizations have that too, the repo name is just `.github`

> I wonder if I can get GitHub Pages to display the latest stable HTML5 build without too much work?

lmao the earlier method was stupid

just put the html5 build in, like, `/docs/build/` and then link `EnigmaEngine.html` in a navbar (navbar is gonna be next commit btw)
if you want the border thingy you can look at the earliest version of this comment but

**Comment by EliteMasterEric** [comment]
> just put the html5 build in, like, `/docs/build/` and then link `EnigmaEngine.html` in a navbar

That's reasonable, but I guess that means that in order to link it with continuous integration (have Github automatically update the build every time I merge into stable), I have to set up a Github Action to update it.

**Comment by isakube** [comment]
> > just put the html5 build in, like, `/docs/build/` and then link `EnigmaEngine.html` in a navbar
> 
> That's reasonable, but I guess that means that in order to link it with continuous integration (have Github automatically update the build every time I merge into stable), I have to set up a Github Action to update it.

look at Puyo's KadeEngineWeb repo, there might be some answers there
edit: nope lol

**Comment by EliteMasterEric** [comment]
https://github.com/EnigmaEngine/enigmaengine.github.io and https://github.com/EnigmaEngine/.github both exist and are accepting PRs (didn't know that organizations could have READMEs, thanks!).

**Comment by isakube** [comment]
> https://github.com/EnigmaEngine/enigmaengine.github.io and https://github.com/EnigmaEngine/.github both exist and are accepting PRs (didn't know that organizations could have READMEs, thanks!).

np :)

**Comment by isakube** [comment]
lmao im stupid

**Pull request closed without merging**
