### PR TITLE
Song Info In Freeplay, Mod List, Other Random Stuff

### PR DESCRIPTION
**Pull request by isakube**
### Additions
- Song Info Popup In Freeplay, press `[SPACE]` to see it
- A working Mod List file. If the file isn't found, it defaults to scanning the `mods` directory like it did prior to this PR. (I just really don't want the Tricky mod, y'know?)

### Changes
- "MFC" is now "SFC" because Marvelous isn't a judgement lol (silly Kade pasting Etterna things)
- Event TYPES no longer have grammar rules???? (I can revert this if you want)

### Removals
- The docs??? (yeah so apparently i started docs work on this branch idfk i just reverted the commits)

---
## Resolves
None found

---

Sub-supreme gaming.

### CODE REVIEW

**Comment by isakube** [comment]
br it doesn't let me fix the conflicts whyyyyyyy

**Comment by isakube** [comment]
god fucking dammit i hate git WHY IS IT COUNTING THE DOC COMMITS GKDFJHDFGSHJKGDFGX LHJGFKHJHLFGSDHDFGLHJKGDFSLHJKSDFGHJKLSDHJKLDDHJKSDFGJHKLGDFSHJKLGFSDJHKLGFSDHJKLDGSFLHJKGSDFJHKLGSDFHJKLGDFSKHJLGDSFHJKLS

**Comment by EliteMasterEric** [comment]
I appreciate your contributions but please let me get the repository in a decent state first, everything's still broken rn.

Also I note that I want to move the documentation out of the wiki completely, please relocate those contributions to the [Github Pages repository I created for you](https://github.com/EnigmaEngine/EnigmaEngine.github.io).

**Comment by isakube** [comment]
> I appreciate your contributions but please let me get the repository in a decent state first, everything's still broken rn.

yea

> Also I note that I want to move the documentation out of the wiki completely, please relocate those contributions to the [Github Pages repository I created for you](https://github.com/EnigmaEngine/EnigmaEngine.github.io).

yeah im gonna migrate stuff over

**Pull request closed without merging**
